application/views.py
import os

from flask import Blueprint, render_template, request, redirect, url_for
import requests

app_bp = Blueprint("app", __name__,
                   template_folder="templates", static_folder='static',
                   static_url_path='/application/static')

#to generate a filename with png extension
def file_name_generate(text):
    if len(text) > 10:
        text = text[:10]
    text_to_generate = str(text).replace(" ", "_")
    filename_with_ext = text_to_generate+".png"
    return filename_with_ext

#to convert the bytes into an output_image
def image_generate_function(image_bytes, output_image):
    try:
        with open(output_image, 'wb') as output_file:
            output_file.write(image_bytes)
        print("Image Created Successfully!!")
    except Exception as e:
        print(e)

@app_bp.route("/")
def home():
    return render_template("index.html")

@app_bp.route("/image_generate", methods=["GET", "POST"])
def image_generate():
    if request.method == "POST":
        text_to_image = request.form["text_to_image"]
        #print(text_to_image)
        image = requests.post('https://clipdrop-api.co/text-to-image/v1',
                              files={
                                  'prompt':(None, text_to_image, 'text/plain')
                              },
                              headers={'x-api-key':os.getenv('API_KEY')})
        if (image.ok):
            output_image = "application/static/images/"+file_name_generate(text_to_image.strip())
            image_bytes = image.content
            image_generate_function(image_bytes, output_image)
        else:
            print(image.raise_for_status())
    return render_template('index.html', data=[{"output_image":file_name_generate(text_to_image.strip())}])

@app_bp.route("/about")
def about():
    return render_template("about.html")

@app_bp.route("/api_reference")
def api_reference():
    return render_template("api_reference.html")

application/templates/about.html
{% extends 'base.html' %}
{% block title %} About The App {% endblock %}
{% block heading %} <span style="color:blue;">ABOUT</span> THE <span style="color:red;">APP</span> {% endblock %}
{% block content %}
<p>Generating images using text, this program or application is simply generated using the <b>Clipdrop API</b> by <b>Arun Arunisto</b>
<br>This app developed using the technologies like Flask for backend, HTML, BOOTSTRAP for frontend.</p>
{% endblock %}

application/templates/api_reference.html
{% extends 'base.html' %}
{% block title %} API REFERENCE {% endblock %}
{% block heading %} <span style="color:blue;">API</span> For <span style="color:red;">Reference</span> {% endblock %}
{% block content %}
<p>API using to create this app is <b>Clipdrop's API</b>
<br>
Generate API KEY by creating an account in Clipdrop, they're providing different tools.
<br>
You'll get 100 free credits for using the API</p>
{% endblock %}

application/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar bg-dark" data-bs-theme="dark">
    <div class="container-fluid justify-content-start">
        <a class="navbar-brand" href="{{ url_for('app.home') }}">Home</a>
        <a class="navbar-brand" href="{{ url_for('app.about') }}">About</a>
        <a class="navbar-brand" href="{{ url_for('app.api_reference') }}">API Reference</a>
    </div>
</nav>
<div class="card text-center" style="border:none;">
    <div class="card-body">
        <h2 class="card-title">{% block heading %} {% endblock %}</h2>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <hr>
    </div>
</div>
<div class="card" style="border:none;">
    <center>
        <div class="card-body" style="width: 75%;">
            {% block content %}
            {% endblock %}
        </div>
    </center>
</div>
<div class="card" style="border:none;">
    <div class="card-body">
        <center>
            {% block images %}
            {% endblock %}
        </center>
    </div>
</div>
</body>
</html>

application/templates/index.html
{% extends 'base.html' %}
{% block title %} Text To Image Generate {% endblock %}
{% block heading %} <span style="color:blue;">TEXT</span> 2 <span style="color:red;">IMAGE</span> {% endblock %}
{% block content %}
<form action="image_generate" method="post">
    <div class="mb-3">
        <input type="text" class="form-control" placeholder="Text to generate an image" name="text_to_image">
    </div>
    <div class="mb-3">
        <button type="submit" class="btn btn-primary mb-3">Generate Image</button>
    </div>
</form>
{% endblock %}
{% block images %}
{% if data %}
{% for i in data %}
<img src="{{url_for('app.static', filename='images/')}}{{i.output_image}}" class="img-fluid" alt="images">
{% endfor %}
{% endif %}
{% endblock %}